FROM node:0.12
MAINTAINER Reittiopas version: 0.1

WORKDIR {{openjourneyplanner_ui_root}}

RUN apt-get update
RUN apt-get install -y git npm

RUN echo "{{ansible_date_time.epoch}}"

# Get latest code
RUN mkdir -p {{openjourneyplanner_ui_root}} && \
  cd {{openjourneyplanner_ui_root}} && \
  git clone {{openjourneyplanner_ui_git}} .

# Build app
RUN npm install && \
  npm run static && \
  npm run build

{% raw %} # HNNGH! - Escaping curly braces for jinja
# Inline css
RUN sed -i '/{{{ style }}}/r _static/css/bundle.css' app/app.html && \
  sed -i 's/{{{ style }}}/<style type="text\/css">/g' app/app.html && \
  sed -i 's/<\/head>/<\/style><\/head>/g' app/app.html
{% endraw %}

CMD export PORT={{openjourneyplanner_ui_exposed_port}}; npm run start
