FROM python:2
MAINTAINER Reittiopas version: 0.1

RUN \
  apt-get update && apt-get install -y \
    git

RUN \
  mkdir -p {{raildigitraffic2gtfsrt_root}} && \
  cd {{raildigitraffic2gtfsrt_root}} && \
  git clone {{raildigitraffic2gtfsrt_git}} . && \
  pip install -r requirements.txt && pip install requests && \
  sed -i -e 's#http://digitransit.fi/route-server/#http://routeserver:{{route_server_exposed_port}}/#' {{raildigitraffic2gtfsrt_root}}/app.py && \
  echo "{{ansible_date_time.epoch}}"

WORKDIR {{raildigitraffic2gtfsrt_root}}

CMD export PORT={{raildigitraffic2gtfsrt_exposed_port}} && export TZ="Europe/Helsinki" && python app.py
