---
- name: Ensure geocoder directory is present
  file: path={{geocoder_root}} state=directory

- name: Update geocoder source
  git: repo={{geocoder_git}} dest={{geocoder_root}}/repo

- name: Move geocoder Dockerfile
  template: src=Dockerfile.j2 dest={{geocoder_root}}/Dockerfile

- name: Build base image
  command: docker build --tag="geocoder" {{geocoder_root}}/repo

- name: Build geocoder image
  command: docker build --tag="{{geocoder_docker_image}}" --force-rm=true {{geocoder_root}}
