FROM {{digitransit_ui_docker_image}}:latest
MAINTAINER Reittiopas version: 0.1

WORKDIR {{digitransit_ui_root}}

ENV CONFIG="hsl"

# Build app
RUN SERVER_ROOT= npm run build

CMD export PORT={{digitransit_ui_exposed_port}}; npm run start
