FROM {{digitransit_ui_docker_image}}:latest
MAINTAINER Reittiopas version: 0.1

WORKDIR {{digitransit_ui_root}}

ENV CONFIG="hsl"

# Build app
RUN SENTRY_DSN={{sentry_dsn}} PIWIK_ID={{digitransit_ui_regional_piwik}} PIWIK_ADDRESS={{piwik_address}} SERVER_ROOT= npm run build

# Start app
CMD export PORT={{digitransit_ui_exposed_port}}; SENTRY_SECRET_DSN={{sentry_secret_dsn}} npm run start
