FROM node:0.12
MAINTAINER Reittiopas version: 0.1

RUN apt-get update
RUN apt-get install -y git npm

RUN \
  mkdir -p {{navigator_server_root}} && \
  cd {{navigator_server_root}} && \
  git clone {{navigator_server_git}} . && \
  # Temporarily remove Helmi data
  sed -i '/helmi_client = new helmi.HelmiClient handle_event/d' src/server.coffee && \
  sed -i '/helmi_client.connect()/d' src/server.coffee && \
  npm install && \
  npm install -g grunt-cli && \
  echo "{{ansible_date_time.epoch}}"

WORKDIR {{navigator_server_root}}

CMD grunt server --port {{navigator_server_exposed_port}} --stack
