---
- name: Ensure map server directory is absent
  file: path={{hsl_map_server_root}} state=absent

- git: repo={{hsl_map_server_git}}
       dest={{hsl_map_server_root}}

- name: Build docker image
  shell: docker build --tag={{hsl_map_server_docker_image|quote}} --force-rm=true {{hsl_map_server_root|quote}} >ansible-hsl-map-server-build.log 2>&1
