---
- name: Ensure map server directory is present
  file: path={{map_server_root}} state=directory

- name: Move Dockerfile
  template: src=Dockerfile.j2 dest={{map_server_root}}/Dockerfile owner=root group=root mode=0755

- name: Move config file
  template: src=config.js.j2 dest={{map_server_root}}/config.js

- name: Build docker image
  shell: docker build --tag={{map_server_docker_image|quote}} --force-rm=true {{map_server_root|quote}} >ansible-map-server-build.log 2>&1
