---
- name: Ensure digitransit-ui directory is present
  file: path={{digitransit_ui_root}} state=directory

- name: Move Dockerfile
  template: src=Dockerfile.j2 dest={{digitransit_ui_root}}/Dockerfile owner=root group=root mode=0755

- name: Build digitransit.ui docker image
  command: docker build --tag="{{digitransit_ui_docker_image}}" --force-rm=true {{digitransit_ui_root}}
