---
- name: Ensure digitransit-ui directory is not present
  file: path={{digitransit_ui_root}} state=absent

- git: repo={{digitransit_ui_git}}
       dest={{digitransit_ui_root}}

- name: Build digitransit.ui docker image
  shell: docker build --tag={{digitransit_ui_docker_image|quote}} --force-rm=true {{digitransit_ui_root|quote}} >ansible-digitransit-ui-build.log 2>&1
