---
- name: Ensure hsl-alert directory is not present
  file: path={{hsl_alert_root}} state=absent

- git: repo={{hsl_alert_git}}
       dest={{hsl_alert_root}}

- name: Build docker image
  shell: docker build --tag={{hsl_alert_docker_image|quote}} --force-rm=true {{hsl_alert_root|quote}} >ansible-hsl-alert-build.log 2>&1
