FROM node:0.12
MAINTAINER Reittiopas version: 0.1

RUN apt-get update
RUN apt-get install -y git npm

RUN mkdir -p {{vector_map_server_root}}

WORKDIR {{vector_map_server_root}}

RUN npm install tessera
RUN npm install tilelive-tmsource
RUN npm install tilelive-xray

RUN echo "{{ansible_date_time.epoch}}" > build_date

RUN git clone {{vector_map_server_style_git}} {{vector_map_server_style}}

RUN sed -i -e 's/host: localhost/host: postgis-osm/' {{vector_map_server_style}}/data.yml
RUN sed -i -e 's/password: postgres/password: mysecretpassword/' {{vector_map_server_style}}/data.yml

EXPOSE {{vector_map_server_exposed_port}}

CMD node node_modules/tessera/bin/tessera.js --port {{vector_map_server_exposed_port}} tmsource://./{{vector_map_server_style}}/

