---
- name: Ensure navigator server directory is not present
  file: path={{navigator_server_root}} state=absent

- git: repo={{navigator_server_git}}
       dest={{navigator_server_root}}

- name: Build docker image
  shell: docker build --tag={{navigator_server_docker_image|quote}} --force-rm=true {{navigator_server_root|quote}} >ansible-navigator-server-build.log 2>&1
