FROM node:0.12
MAINTAINER Reittiopas version: 0.1

RUN apt-get update
RUN apt-get install -y git npm

RUN mkdir -p {{map_server_root}}

WORKDIR {{map_server_root}}

RUN npm install tessera
RUN npm install tilelive-tmstyle
RUN npm install tilelive-http

RUN echo "{{ansible_date_time.epoch}}" > build_date

RUN git clone {{map_server_style_git}} {{map_server_style}}

RUN echo '{ "/hsl-map": "tmstyle://./{{map_server_style}}/"}' > config.json

CMD node node_modules/tessera/bin/tessera.js --config config.json --port {{map_server_exposed_port}}
