FROM node:4
MAINTAINER Reittiopas version: 0.1

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y git libgl1-mesa-glx xserver-xorg-video-dummy unzip

RUN mkdir -p {{map_server_root}}

WORKDIR {{map_server_root}}

RUN echo "{{ansible_date_time.epoch}}" > build_date

RUN npm install tessera \
  tilejson \
  tilelive-http \
  tilelive-otp-stops \
  tilelive-hsl-parkandride \
  mbtiles \
  tilelive-xray \
  forever

RUN curl https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v1.0/extracts/finland.mbtiles > finland.mbtiles

RUN curl http://xpra.org/xorg.conf > xorg.conf

RUN npm install https://github.com/hannesj/tilelive-gl.git

RUN npm install https://github.com/HSLdevcom/hsl-map-style.git

RUN cd {{map_server_root}}/node_modules/hsl-map-style && \
  unzip -P {{fontstack_zip_password}} fontstack.zip && \
  sed -i -e 's#/Users/hannes/hsl-map-generator/#{{map_server_root}}/node_modules/#' hsl-gl-map-v8.json && \
  sed -i -e 's#localhost:8000/#localhost:{{map_server_exposed_port}}/hsl-vector-map/#' hsl-gl-map-v8.json

COPY config.js {{map_server_root}}/

EXPOSE {{map_server_exposed_port}}

CMD Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./10.log -config ./xorg.conf :10 & \
  sleep 15 && \
  DISPLAY=":10" node_modules/.bin/forever start -c "node --harmony" \
  node_modules/tessera/bin/tessera.js --port {{map_server_exposed_port}} --config config.js \
  -r {{map_server_root}}/node_modules/tilelive-otp-stops/ \
  -r {{map_server_root}}/node_modules/tilelive-gl/ \
  -r {{map_server_root}}/node_modules/tilelive-hsl-parkandride \
  && sleep 10 && node_modules/.bin/forever --fifo logs 0
