FROM node:0.12
MAINTAINER Reittiopas version: 0.1

RUN apt-get update
RUN apt-get install -y git npm

RUN \
  mkdir -p {{navigator_proto_root}} && \
  cd {{navigator_proto_root}} && \
  git clone {{navigator_proto_git}} . && \
  npm install && \
  npm install -g grunt-cli && \
  echo "{{ansible_date_time.epoch}}"

ADD local_config.coffee {{navigator_proto_root}}/src/local_config.coffee

WORKDIR {{navigator_proto_root}}

CMD grunt server --port {{navigator_proto_exposed_port}}
