---
- name: Ensure siri2gtfsrt directory is not present
  file: path={{siri2gtfsrt_root}} state=absent

- git: repo={{siri2gtfsrt_git}}
       dest={{siri2gtfsrt_root}}

- name: Build docker image
  shell: docker build --tag={{siri2gtfsrt_docker_image|quote}} --force-rm=true {{siri2gtfsrt_root|quote}} >ansible-siri2gtfsrt-build.log 2>&1
