FROM maven:3-jdk-8
MAINTAINER Reittiopas version: 0.1

RUN \
  apt-get update && \
  apt-get install -y git

# Fetch maven dependencies
RUN \
  mkdir -p {{otp_root}} && \
  cd {{otp_root}} && \
  rm -rf * && \
  git clone {{otp_git}} . && \
  mvn dependency:resolve

# Build OTP
RUN \
  cd {{otp_root}} && \
  git pull && \
  mvn clean package && \
  echo "{{ansible_date_time.epoch}}"

ADD run.sh {{otp_root}}/run.sh

ADD router-config.finland.json {{otp_root}}/router-config.finland.json
ADD router-config.hsl.json {{otp_root}}/router-config.hsl.json
ADD build-config.json {{otp_root}}/build-config.json

WORKDIR {{otp_root}}

CMD ./run.sh
