---
- name: Ensure otp-data-container directory is absent
  file: path={{otp_data_container_root}} state=absent

- git: repo={{otp_data_container_git}}
       dest={{otp_data_container_root}}

- name: Build otp-data-container image
  shell: docker build --build-arg MATKA_PASSWORD={{matka_basic_auth}} --build-arg HSL_PASSWORD={{hsl_basic_auth}} --tag={{otp_data_container_docker_image|quote}} --force-rm=true {{otp_data_container_root|quote}} >ansible-otp-data-container.log 2>&1
