FROM debian:jessie
MAINTAINER Reittiopas version: 0.1

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN groupadd -r postgres && useradd -r -g postgres postgres

# grab gosu for easy step-down from root
RUN gpg --keyserver pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* \
	&& curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture)" \
	&& curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/1.2/gosu-$(dpkg --print-architecture).asc" \
	&& gpg --verify /usr/local/bin/gosu.asc \
	&& rm /usr/local/bin/gosu.asc \
	&& chmod +x /usr/local/bin/gosu \
	&& apt-get purge -y --auto-remove curl

# make the "en_US.UTF-8" locale so postgres will be utf-8 enabled by default
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
ENV PG_MAJOR 9.4
ENV POSTGIS_MAJOR 2.1

RUN mkdir /docker-entrypoint-initdb.d

RUN apt-key adv --keyserver pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' > /etc/apt/sources.list.d/pgdg.list

RUN apt-get update \
	&& apt-get install -y postgresql-common \
	&& sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf \
	&& apt-get install -y \
		postgresql-9.4 \
		postgresql-contrib-9.4 \
		postgresql-9.4-postgis-2.1 \
		postgis \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/postgresql && chown -R postgres /var/run/postgresql

RUN mkdir -p /var/lib/postgresql/data

ENV PATH /usr/lib/postgresql/$PG_MAJOR/bin:$PATH
ENV PGDATA /var/lib/postgresql/data

RUN mkdir -p /docker-entrypoint-initdb.d

RUN apt-get update && apt-get install -y git imposm ca-certificates wget gdal-bin && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /home/reittiopas/docker/postgis-osm

WORKDIR /home/reittiopas/docker/postgis-osm

RUN echo "{{ansible_date_time.epoch}}"

RUN git clone {{vector_map_server_style_git}}
RUN git clone https://github.com/mapbox/postgis-vt-util.git

COPY docker-entrypoint.sh /
COPY initdb-postgis.sh /docker-entrypoint-initdb.d/00-postgis.sh
COPY initdb-osm-data.sh /docker-entrypoint-initdb.d/50-osm-data.sh

RUN /docker-entrypoint.sh postgres

EXPOSE 5432

CMD ["gosu", "postgres", "postgres"]