---
- name: Ensure directory is not present
  file: path={{raildigitraffic2gtfsrt_root}} state=absent

- git: repo={{raildigitraffic2gtfsrt_git}}
       dest={{raildigitraffic2gtfsrt_root}}

- name: Build docker image
  shell: docker build --tag={{raildigitraffic2gtfsrt_docker_image|quote}} --force-rm=true {{raildigitraffic2gtfsrt_root|quote}} >ansible-raildigitraffic2gtfsrt-build.log 2>&1
