FROM nginx

MAINTAINER Reittiopas version: 0.1

RUN mkdir -p {{reverse_proxy_root}}

RUN mkdir -p {{reverse_proxy_root}}/cache

RUN mkdir -p {{reverse_proxy_root}}/site

ADD proxy.conf /etc/nginx/nginx.conf
ADD common.conf /etc/nginx/common.conf

RUN chown -R nginx:nogroup {{reverse_proxy_root}}

# gpg keys listed at https://github.com/nodejs/node
RUN set -ex \
  && for key in \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
  ; do \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
  done

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 5.5.0

RUN apt-get update \
  && apt-get install curl git python build-essential -y \
  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --verify SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-x64.tar.gz\$" SHASUMS256.txt.asc | sha256sum -c - \
  && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-x64.tar.gz" SHASUMS256.txt.asc

RUN git clone {{site_git}} {{reverse_proxy_root}}/site \
  && cd {{reverse_proxy_root}}/site \
  && npm install -g gatsby@0.7.7 \
  && npm install \
  && gatsby build \
  && echo "{{ansible_date_time.epoch}}"

WORKDIR /etc/nginx

CMD ["nginx"]
