FROM debian:wheezy

MAINTAINER Reittiopas version: 0.1

RUN apt-key adv --keyserver pgp.mit.edu --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
RUN echo "deb http://nginx.org/packages/mainline/debian/ wheezy nginx" >> /etc/apt/sources.list

ENV NGINX_VERSION 1.7.10-1~wheezy

RUN apt-get update && \
    apt-get install -y ca-certificates nginx=${NGINX_VERSION} && \
    rm -rf /var/lib/apt/lists/*

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

VOLUME ["/var/cache/nginx"]

RUN mkdir -p {{reverse_proxy_root}}

ADD proxy.conf /etc/nginx/nginx.conf

ADD index.html {{reverse_proxy_root}}/index.html

ADD img {{reverse_proxy_root}}/img

ADD css {{reverse_proxy_root}}/css

WORKDIR /etc/nginx

CMD ["nginx"]
