FROM node:0.12
MAINTAINER Reittiopas version: 0.1

WORKDIR {{digitransit_ui_root}}

RUN apt-get update
RUN apt-get install -y git npm

# Get initial (cacheable) code
RUN mkdir -p {{digitransit_ui_root}} && \
  cd {{digitransit_ui_root}} && \
  git clone {{digitransit_ui_git}} . && \
  npm install

RUN echo "{{ansible_date_time.epoch}}"

# Get latest code
RUN git pull

ENV ROOT_PATH="/digitransit-ui/"

# Build app
RUN npm install && \
  npm run static && \
  npm run build

CMD export PORT={{digitransit_ui_exposed_port}}; npm run start
