FROM node:0.12
MAINTAINER Reittiopas version: 0.1

WORKDIR {{digitransit_ui_root}}

RUN apt-get update
RUN apt-get install -y git libglew-dev

RUN npm install -g npm@3

# reset cache monthly
RUN echo "{{ansible_date_time.month}}"

# Get initial (cacheable) code
RUN mkdir -p {{digitransit_ui_root}} && \
  cd {{digitransit_ui_root}} && \
  git clone {{digitransit_ui_git}} . && \
  npm install

# Get latest code
RUN git pull && echo "{{ansible_date_time.month}}"

ENV ROOT_PATH=""

# Build app, use current host as SERVER_ROOT
RUN npm install && \
  npm run static && \
  SENTRY_DSN={{sentry_dsn}} PIWIK_ID={{digitransit_ui_national_piwik}} PIWIK_ADDRESS={{piwik_address}} SERVER_ROOT={{digitransit_ui_national_server_root}} npm run build

CMD export PORT={{digitransit_ui_exposed_port}}; SENTRY_SECRET_DSN={{sentry_secret_dsn}} SERVER_ROOT={{digitransit_ui_national_server_root}} npm run start
