---
- name: Ensure otp directory is not present
  file: path={{otp_root}} state=absent

- git: repo={{otp_git}}
       dest={{otp_root}}

- name: Build docker image
  shell: docker build --tag={{otp_docker_image|quote}} --force-rm=true {{otpt_root|quote}} >ansible-otp-build.log 2>&1
