FROM node:0.12
MAINTAINER Reittiopas version: 0.1

RUN \
  apt-get update && \
  apt-get install -y git && \
  apt-get install -y python-pip && \
  pip install transitfeed && \
  pip install protobuf && \
  pip install flask && \
  pip install python-dateutil && \
  pip install pytz

RUN \
  mkdir -p {{siri2gtfsrt_root}} && \
  cd {{siri2gtfsrt_root}} && \
  git clone {{siri2gtfsrt_git}} . && \
  echo "{{ansible_date_time.epoch}}"

ENV CHAIN_URL=http://raildigitraffic2gtfsrt:{{raildigitraffic2gtfsrt_exposed_port}}/hsl
ENV TRIP_UPDATE_URL=http://hslalert:{{hsl_alert_exposed_port}}/

EXPOSE {{siri2gtfsrt_exposed_port}}

WORKDIR {{siri2gtfsrt_root}}

CMD export PORT={{siri2gtfsrt_exposed_port}} && \
    export HSL_URL=http://navigatorserver:{{navigator_server_exposed_port}}/siriaccess/vm/json?operatorRef=HSL && \
    python siri2gtfsrt.py
